mingw="/c/Program\ Files/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/bin"
alias gcc="$mingw/gcc.exe"
alias g++="$mingw/g++.exe"
alias make="$mingw/mingw32-make.exe"
alias gdb="$mingw/gdb.exe"
